-------------------------------------------------------------------------------
Test set: dao.Sql2oUsersDaoTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.446 sec <<< FAILURE! - in dao.Sql2oUsersDaoTest
dao.Sql2oUsersDaoTest  Time elapsed: 0.446 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "adwesh"
	at dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:23)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "adwesh"
	at dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:23)

dao.Sql2oUsersDaoTest  Time elapsed: 0.446 sec  <<< ERROR!
java.lang.NullPointerException
	at dao.Sql2oUsersDaoTest.shutDown(Sql2oUsersDaoTest.java:36)

